name: sitesaarthi
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  lucide_icons_flutter: ^1.2.6
  google_fonts: ^6.2.1
  package_info_plus: ^8.0.2
  go_router: ^14.6.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  pdf: ^3.10.7
  printing: ^5.11.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/SiteSaarthiLogo.png
    - assets/assistant.png
